### PR TITLE
Add linter to chapter3

### PR DESCRIPTION
**Pull request by funkyboy**
Closes https://github.com/raywenderlich/flta/issues/97

### CODE REVIEW

**Review by Stef-GMS — COMMENTED** [review]
Google prefers trailing commas and it looks like instead of adding those new line was used.

**Comment by funkyboy** [comment]
@Stef-GMS you mean this PR introduces new lines instead of commas somewhere?

**Comment by Stef-GMS** [comment]
It looked like it reading the PR review.  I'm pulling the code into A.S. to confirm.

**Review by Stef-GMS — APPROVED** [review]
Approved

**Pull request merged**
