### PR TITLE
Add linter to chapter2

### PR DESCRIPTION
**Pull request by funkyboy**
Closes https://github.com/raywenderlich/flta/issues/96

### CODE REVIEW

**Review by Stef-GMS — APPROVED** [review]
The analysis_options.yaml file looks OK.  I'm not sure about the .xml files, but assume they're OK.

**Review by Stef-GMS — APPROVED** [review]
Approved, except for test folder which should be removed if we're not using widget tests.

**Review by Stef-GMS — APPROVED** [review]
Approved, except for test folder which should be removed if we're not using widget tests.

**Review by Stef-GMS — APPROVED** [review]
Approved, except for test folder which should be removed if we're not using widget tests.

**Review by Stef-GMS — CHANGES_REQUESTED** [review]
If we're not doing anything with the tests, which it looks like we're not because this is the default, then the test folder could be deleted.

**Review by Stef-GMS — CHANGES_REQUESTED** [review]
If we're not using the widget tests then the test folder and file should be removed.

**Review by Stef-GMS — CHANGES_REQUESTED** [review]
If we're not using the widget tests then the test folder and file should be removed.

**Review by Stef-GMS — CHANGES_REQUESTED** [review]
Approved, except for test folder which should be removed if we're not using widget tests.

**Comment by funkyboy** [comment]
@Stef-GMS test folder removed. See https://github.com/raywenderlich/flta-materials/pull/44/commits/c47f8f46b911f3ab6a1962ed15fef1aef39b6f64

**Pull request merged**
