### PR TITLE
Suggestions

### PR DESCRIPTION
**Pull request by marcelmfa**
Just in case if you want add this challenge in Chapter 6.

### CODE REVIEW

**Comment by marcelmfa** [comment]
I've changed a check to outside a anonymous function, since isn't a Future data. Simple thing.

**Review by kevindmoore — APPROVED** [review]

**Comment by funkyboy** [comment]
@marcelmfa thanks for your suggestion. Really appreciate it.
We can't merge your changes as is, 'cause we'll need to port them also in subsequent chapters and likely adjust some of the text in the book. 
We'll keep this PR around so we can include your suggestions when we make a new release of the book. 
Thanks again!

**Comment by marcelmfa** [comment]
> @marcelmfa thanks for your suggestion. Really appreciate it. We can't merge your changes as is, 'cause we'll need to port them also in subsequent chapters and likely adjust some of the text in the book. We'll keep this PR around so we can include your suggestions when we make a new release of the book. Thanks again!

no problem at all @funkyboy. Thanks for feedback and if I have any more suggestions, I'll include in this same PR with a specific commit message.

Best Regards

**Comment by mkabdullahi** [comment]
I would like to point out an image rendering error causes by wrong file extension in chapter 3 (03-basic-widgets). I was practicing and I realised that the profile image in folder[/assets/]  "author_katz.jpeg" was suppose to be "author_katz.jpg" kindly correct it.

**Comment by funkyboy** [comment]
Thanks @habibu 
Please post this on the forums https://forums.raywenderlich.com/c/books/flutter-apprentice/68
That's were we handle all the feedback.
Cheers :)

**Comment by funkyboy** [comment]
We are in the process of updating the book. We'll keep these suggestions into account. Thanks.

**Pull request closed without merging**
